. setup.sh

echo "\$PROJECTNAME: $PROJECTNAME"
echo "\$DBNAME: $DBNAME"
echo "\$DBUSER: $DBUSER"
echo "\$DBPASSWORD: $DBPASSWORD"
echo "\$PROJECTMODULE: $PROJECTMODULE"
echo "\$WORKSPACE: $WORKSPACE"
echo "\$VIRTUAL_ENV_REQUIREMENTS: $VIRTUAL_ENV_REQUIREMENTS_FILE"

